language: node_js

node_js:
  - "9"
  - "8"
  - "6"
    # don't run ts tests on node 6
    script:
      - npm run test:js
  - "10"

notifications:
  email:
    on_success: never
    on_failure: always
